services:
  server:
    build:
      context: ./server
      target: dev
    environment:
      AUTH_TRUST_HOST: true
      DYNAMO_DB_HOST: dynamodb
      DYNAMO_DB_PORT: 8000
      DYNAMO_DB_REGION: "eu-central-1"
      DYNAMO_DB_TABLE: "Transactions-QA"
    ports:
      - 3000:3000
    depends_on:
      - dynamodb
    volumes:
      - ./server:/usr/src/avar
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data --cors 'http://server:3000'"
    image: "amazon/dynamodb-local:2.4.0"
    container_name: dynamodb
    ports:
      - 8000:8000
    volumes:
      - "./db/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
